version: '{branch}-build-{build}'

shallow_clone: true

install:
  - perl -V

test: off

build_script:
  - perl Build.PL
  - Build installdeps --cpan_client "cpan -T"
  - Build manifest
  - dir
  - cd devel.utils
  - build-5.26-test.bat
  - dir
  - cd ..
  - dir

artifacts:
  - path: ..\..\strawberry_build\output\*.zip
    name: logs
