version: '{branch}-build-{build}'

shallow_clone: true

install:
  - perl -V

test: off

build_script:
  - mv -vf "C:\OpenSSL-Win32" "C:\OpenSSL-Win32.dont-use"
  - mv -vf "C:\OpenSSL-Win64" "C:\OpenSSL-Win64.dont-use"
  - perl Build.PL
  - Build installdeps --cpan_client "cpan -T"
  - Build manifest
  - dir
  - cd devel.utils
  - build-5.26-test.bat
  - dir
  - cd ..
  - dir

artifacts:
  - path: tmp_build\output\*.zip
    name: logs
