version: '{branch}-build-{build}'

shallow_clone: true

install:
  - perl -V
  - cinst wixtoolset --install-dir="C:\WixToolSet"

test: off

build_script:
  - perl Build.PL
  - Build installdeps --cpan_client "cpan -T"
  - Build manifest
  - dir
  - cd devel.utils
  - build-5.26-test.bat
  - dir
  - cd ..
  - dir
