version: '{branch}-build-{build}'

shallow_clone: true

install:
  - cinst wixtoolset
  - perl --version

test: off

build_script:
  - perl Build.PL
  - Build installdeps --cpan_client 'cpan -T'
  - Build manifest
  - dir
  - cd devel.utils
  - build-5.26.bat
  - dir
  - cd ..
  - dir
