version: '{branch}-build-{build}'

shallow_clone: true

install:
  - perl -V

test: off

build_script:
  - mv -vf "C:\OpenSSL-Win32" "C:\OpenSSL-Win32.dont-use"
  - mv -vf "C:\OpenSSL-Win64" "C:\OpenSSL-Win64.dont-use"
  - perl Build.PL
  - rem make dir C:\tmp to fix Data::UUID install
  - mkdir C:\tmp
  - Build installdeps --cpan_client "cpan -T"
  - Build manifest
  - dir
  - cd devel.utils
  - build-5.28-test.bat
  - dir
  - cd ..
  - dir

artifacts:
  - path: tmp_build\output\*debug_dir.zip,tmp_build\output\*LOG.zip,
    name: logs
  - path: tmp_build\output\strawberry-perl*-64bit.zip,tmp_build\output\strawberry-perl*-64bit-portable.zip,tmp_build\output\strawberry-perl*-32bit.zip,tmp_build\output\strawberry-perl*-32bit-portable.zip
    name: zip
  - path: tmp_build\output\strawberry-perl*-64bit.msi
    name: msi
